name: Update RSS Feeds
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Run workflow manually, from Github Actions tab

jobs:
  update-readme-with-blog:
    name: Update an MD file from an RSS feed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch RSS feed
        uses: risadams/update-md-rss@v1.0.0
        with:
          feed_list: 'https://risadams.com/feed.xml' ## Update this with your feed URL
